### ISSUE TITLE
アイテム取得に失敗してもそのまま利用できるようにする

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/TCV#113]
おかしな応答が返ってきても、アイテム取得以外の機能が正しく動くように使用。

**Comment by kitabatake1013** [comment]
アイテム取得に失敗すると例外で落ちる問題は直しました。
ただし、状況によってアイテム名・アイテムID・アイテム数の対応関係がずれる問題がまだ残っています。

**Comment by kitabatake1013** [comment]
特に問題が起きているようには見えないのでクローズします。
