### ISSUE TITLE
カスタムURLスキーマに対応する

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/TCV#115]
レジストリ登録で以下のようなことができそうです。
１．twitterなどからツイキャスの配信ページを開く。
２．配信ページのアドレスバーの先頭にtcv://を追加してエンターキーを押すとTCVが起動する。

カスタムURLスキーマという機能を使います。lampのように登録ボタンをメニュー内に設ければいいと思います。

参考: https://garafu.blogspot.com/2014/02/url.html

**Comment by yamahubuki** [comment]
こちらもリリース済みのためクローズします。
