### ISSUE TITLE
アカウント認証時に[キャンセル]ボタンが押された際の処理

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/TCV#12]

**Comment by yamahubuki** [comment]
@kitabatake1013
本件対応のため、implicitGrantManagerをv1.1.0に更新しました。
こちらを利用して対処願います。

**Comment by yamahubuki** [comment]
@kitabatake1013

 これ終わってるのでは？
動作確認取れ次第クローズしてください。

**Comment by kitabatake1013** [comment]
あれ？クローズしてなかったのか...
大分前に動作確認は終わっているので、クローズしておきます。
