### ISSUE TITLE
一時的に通知を停止するショートカット

### ISSUE THREAD

**Issue by hrk-fujii** [actlaboratory/TCV#15]
スクリーンリーダに対するコメントなどの通知をスリープする機能が必要と思われる
TCVの通知文字列の割り込みにより元の読み上げが上書きされ、スクリーンリーダ操作ができない

**Comment by kitabatake1013** [comment]
読み上げ先の規定値をSAPI5に変更し、同様の状況になることを防ぐ。
また、マニュアル作成時にその旨を明記する。
読み上げを一時的に無効化するホットキーは、当面実装しない。
