### ISSUE TITLE
ライブ再生が頻繁に停止する

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/TCV#20]
旧TCV、LAMPなど、bassを使用している多くのアプリケーションで同様の現象が発生。
Foobar2000など、ffmpegを使用していればこの問題は発生しない。
再生機能をTCVに搭載するかどうかも含めて、対応を検討する。

**Comment by yamahubuki** [comment]
とりあえず管理者権限で実行していればこの問題は発生しないようである。
また、Windowsのバージョンが2004以降であることも発生条件かもしれない。

**Comment by yamahubuki** [comment]
上記により解決済み
