### ISSUE TITLE
お気に入り画面で項目がないときに削除が実行されてしまう

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/TCV#23]
次の操作をすると例外が発生する。
1.なんらかのユーザーをお気に入りに追加する。
2.お気に入り一覧を開く。
3.お気に入り一覧にてすべての項目の削除を実行する。
4.その状態でもう一度削除を実行する。

<error>
Traceback (most recent call last):
  File "C:\Users\keigo\Documents\python\tcv\views\viewFavorites.py", line 42, in delete
    dlg = simpleDialog.yesNoDialog(_("確認"), _("%sのライブをお気に入りから削除してもよろしいですか？") %(globalVars.app.Manager.favorites[self.favoritesList.GetFocusedItem()]))
IndexError: list index out of range

**Comment by kitabatake1013** [comment]
先ほど、お気に入りと履歴の表示にリストボックスを使用するように変更を行い（ ea1cc0d319f67e5484a85b660460c8db677ed168 ）、こちらの不具合も合わせて修正しました。
リスト項目の選択状態に応じて、表示されるボタンが変化するようになりました。
