### ISSUE TITLE
tcv.pyで翻訳対象のメッセージが作れない

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/TCV#32]
tcv.py上で、
_("message")
の形式でメッセージを書くと、正しく機能しない。
同ファイル内に「_」という関数が定義されており、そちらが実行されてしまうためと考えられる。

**Comment by yamahubuki** [comment]
この件、　@yncat に確認したところ、削除しても問題ないとのことでした。

翻訳の初期化前に呼ばれる可能性には十分注意したうえで、必要な実装を行って構いません。
