### ISSUE TITLE
アカウントの追加ができない

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/TCV#34]
アカウントマネージャでアカウント追加時にブラウザではauthorisation successfulが表示されるのですがアプリケーション側ではブラウザでの操作を待っていますとなってしまいさきにすすみません。

**Comment by kitabatake1013** [comment]
具体的な再現手順や環境を明記してください。
少なくとも、こちらでは正しく動作しており、再現できません。

**Comment by kitabatake1013** [comment]
現象確認しました。
詳細は、下記の通りです。
近日中に原因を究明して修正します。

### 再現手順

1. アカウントマネージャで[追加]ボタンを押して、ブラウザを起動する。
2. 何も操作せずにブラウザを閉じて、[キャンセル]ボタンを押す。
3. 再び[追加]ボタンを押してブラウザを起動する。
4. [連携アプリを許可]を実行する。

### 期待される動作

アカウントの追加が正常に終了する

### 実際の動作

アカウントの追加が完了せず、処理待ちの状態になる

**Comment by kitabatake1013** [comment]
上記の手順2.を行った際に、implicitGrantManagerのサーバーが終了していないことが原因のようです。
これを回避するには、implicitGrantManagerへの機能追加が必要と思われます。

**Comment by yamahubuki** [comment]
implicitGrantManagerをv1.20にバージョンアップし、shutdown()関数を公開しました。
これを使ってください。
