### ISSUE TITLE
各タイマータイプに名前を付ける

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/TCV#36]
タイマーのモードが３つあるが、それぞれにより簡潔な呼び名を付ける。
現状は、暫定的に、旧バージョンのマニュアルからコピーした下記の文言を使用している。

* コインの枚数を加味せず30分を計測
* コインの枚数を加味して最大まで延長したと仮定した残り時間を計測し各枠ごとの残り時間を詳細に通知する
* コインの枚数を加味して最大まで延長したと仮定した残り時間を計測し延長が予定される枠の残り時間は３分前のみを通知する

これでは非常に長く、動作を理解することが難しく、更に翻訳も大変困難である。
そこで、更に簡潔な表現を考える。

**Comment by yamahubuki** [comment]
#42 でとりあえず文字列を短くしました。

**Comment by kitabatake1013** [comment]
下記のように変更しました。

- 常に30分を計測
- 各枠ごとの残り時間を詳細に通知
- 延長可能な枠では３分前のみ通知
