### ISSUE TITLE
コイン枚数に応じた読み上げの追加

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/TCV#39]
ライブ開始時
「"完走に必用なコインが集まっています。"

アイテム投下時
コインが５枚集まりました。
完走に必要なコインが集まりました。

**Comment by kitabatake1013** [comment]
接続時にすでに4時間分のコインがあった際の読み上げは動作確認済みです。
途中でコインが集まった際の読み上げは未確認です。

**Comment by yamahubuki** [comment]
35枚、動作確認いたしました。

**Comment by yamahubuki** [comment]
一応、今度「数回延長済みで、残り時間分投げた」ケースをテストします。

**Comment by yamahubuki** [comment]
現状では、５の倍数米で読み上げがありますが、複数枚を同時に検知した場合において、合計が一気に５の倍数を超えた場合には読み上げがスキップされてしまっています。
