### ISSUE TITLE
SAPI設定ダイアログを開く機能をつける

### ISSUE THREAD

**Issue by guredora403** [actlaboratory/TCV#50]

**Comment by kitabatake1013** [comment]
FileNotFoundErrorが発生する。
同じことをコマンドプロンプトから行うと正しく動く。
pythonのインタラクティブモードでは動かない。
subprocessを使っていることが原因かもしれない。

**Comment by yamahubuki** [comment]
syswow64指定外してsystem32ならでやって、そこの設定がTCVからの読み上げに反映されるか確認してみてください。

また、exe版だとうまくいく可能性もあります。

**Comment by kitabatake1013** [comment]
system32の方でもTCVの読み上げ音声を変更できますが、TCVからこのCPLファイルを開くことはやはりできませんでした。
この状況はexe版でも同じです。
