### ISSUE TITLE
接続と履歴のダイアログを統合する

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/TCV#75]

**Comment by kitabatake1013** [comment]
以下のような仕様はどうでしょう。

* [接続]ダイアログは常にエディットコンボ
* [設定]→[一般]に、[接続ダイアログに表示する項目]という設定を追加する
* 選択肢は以下の３つ。
    * なし：エディットコンボには何も表示しない（規定値）
    * 履歴：[接続履歴]ダイアログに出しているものと同じように、新しい順に表示する
    * お気に入り：[お気に入りライブ]の内容を表示
* いずれの場合も、新たなIDを入力することはもちろん可能
* 履歴、お気に入りのメニュー項目は削除せず、現状と同じように動作させる

**Comment by yamahubuki** [comment]
よさげです。

**Comment by kitabatake1013** [comment]
先ほどのコメント通りに実装しました。
ただし、接続履歴を規定値にしました。
