### ISSUE TITLE
起動中に受け取ったもののみでよいので、各アイテムを投げたユーザの履歴を確認できるようにする。

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/TCV#83]

**Comment by kitabatake1013** [comment]
これはUIの検討も含めて時間がかかり、新たな不具合を引き起こす恐れもあるので、今後のバージョンアップでの追加を検討します。
今回リリースするバージョンには追加しません。

**Comment by kitabatake1013** [comment]
実装を終えたのでクローズしましたが、以下の課題が残っているため再度オープンします。

- [アイテム履歴]ダイアログのレイアウト調整
- [アイテム履歴]からユーザ情報を確認できるようにする

**Comment by yamahubuki** [comment]
レイアウト調整まで完了したのでクローズします。
