### ISSUE TITLE
アップデートパッケージに更新履歴やヘルプファイルが含まれていない

### ISSUE THREAD

**Issue by riku22** [actlaboratory/TCV#95]
直し方がわからなかったので、とりあえず、問題の報告だけいたします。
先ほどTCVを起動したところ、Version 3.0.1のアップデートがあったので、更新を行いました。
しかし、プログラム自体は更新されているものの、「history.txt」および「readme.txt」が更新されていないようで、Version 3.0.0のままのようでした。
そこで、アップデート時にダウンロードされたパッケージを確認したところ、これらのファイルが含まれていないようでした。
もし可能でしたら、修正いただけないでしょうか。
よろしくお願いいたします。

**Comment by yamahubuki** [comment]
ご連絡ありがとうございます。
アップデートパッチ自動生成の設定ミスでした。
先程別の不具合修正と合わせ、Version3.0.2の配信をして対処させて頂きました。
